### ISSUE TITLE
Drop Icinga DB special case

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/docker-icingaweb2#46]
... once there’s a tag to be used and pinned to until next tag (as with other mods). I.e. remove:

https://github.com/Icinga/docker-icingaweb2/blob/1c41f9c5cd3d65b79f54e82857a891e7922dbeb9/get-mods.sh#L17-L19

**Comment by julianbrost** [comment]
This special case makes the current `icinga/icingaweb2:master` container pretty much unusable (at least if the icingadb module is enabled), instead of the sidebar, you only see the following error message:

```
Fatal error: Declaration of Icinga\Module\Icingadb\Model\Behavior\ReRoute::rewriteCondition(Icinga\Data\Filter\FilterExpression $expression, $relation = NULL) must be compatible with ipl\Orm\Contract\RewriteFilterBehavior::rewriteCondition(ipl\Stdlib\Filter\Condition $condition, $relation = NULL) in /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Model/Behavior/ReRoute.php on line 10
```

Replacing this by `REF=master` resolves this issue for me. I don't know why this was pinned to a specific commit in the first place though.
